repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-shebang-scripts-are-executable
      - id: check-toml
      - id: detect-private-key
      - id: fix-byte-order-marker
      - id: mixed-line-ending
  - repo: https://github.com/kahnwong/pre-commit
    rev: "b7510cc"
    hooks:
      # -- python -- #
      - id: ruff-check
      - id: ruff-format
      - id: mypy
      - id: nbstripout
      - id: yamlfmt
      - id: hadolint
        args:
          - --ignore
          - DL3025
          - --ignore
          - DL3018
          - --ignore
          - DL3027
      - id: trufflehog
#  - repo: local
#    hooks:
#     - id: pytest
#       name: pytest
#       entry: pytest tests/tests.py
#       language: system
#       types: [python]
#       pass_filenames: false
#       require_serial: true
